### ISSUE TITLE
OEM remote

### ISSUE THREAD

**Issue by andrew867** [notpike/The-Fonz#1]
SUZOHAPP has the original remote for just a little more than the third party one (in case someone is looking to purchase one outside the USA, ex: Canada):

https://na.suzohapp.com/products/jukebox_audio_equipment/600069-001

**Comment by notpike** [comment]
Cool thanks! Yah I've had success using the 3rd party remote on various devices and I've been successfull with the script as well. I've been looking into usb receivers for the TouchTunes TBH.

**Comment by andrew867** [comment]
You should be able to make your own USB transceiver using a hardware ASK/OOK module and an Arduino for minimal cost, I just submitted another issue/comment about it. You'd be able to easily just set up the hardware for the frequency and modulation parameters then use the Arduino USB serial interface to send and receive the data directly and do the hard work in python.
