### ISSUE TITLE
Custom hardware implementation

### ISSUE THREAD

**Issue by andrew867** [notpike/The-Fonz#2]
Has anyone attempted using an microcontroller (Arduino) and a hardware ASK/OOK chip like this:
http://www.ebay.ca/itm/201544157440

It would be neat to make your own remote with brute force capability using an Arduino Nano and one of those boards (cheaper than a Yard Stick One and a real remote).

**Comment by andrew867** [comment]
I also found a USB dongle that uses the CC1101, you can configure it in a UART mode (AT commands) then switch it back to a serial passthrough mode:
http://www.ebay.ca/itm/201725104033

**Comment by notpike** [comment]
Cool!
