### ISSUE TITLE
PandwaRF

### ISSUE THREAD

**Issue by bhmayor** [notpike/The-Fonz#3]
To whom it shall concern:

Can anyone provide a short disquisition on the efficacy of this software to execute and function with a PandwaRF device instead of a Yard Stick One?

I presume once the pin number for a TouchTunes Box is known the software is not needed to program a remote control that is purchased, as it can be done manually, no?

Can the software and a PandwaRF (or Yard Stick One) be used to send the pin and other commands to the TouchTunes box?

And YES..by the way, I do remember watching the malachi crunch the night it was first broadcast!

Thanks in advance!

**Comment by notpike** [comment]
Just updated the script so it can be imported as a class threw RfCat. Hopefully this will be useful to those who use PandwaRF.

To make this work all you would need to know is put 'The_Fonz.py' in the same directory as 'rfcat' and do the following...

root@lol:~# ./rfcat -r
>> import The_Fonz as f
>> f.MainMenu()
