### ISSUE TITLE
HackRF Support?

### ISSUE THREAD

**Issue by Tech2025** [notpike/The-Fonz#6]
Wondering if this could work with a HackRF and not only a Yardstick One.

**Comment by mattie02** [comment]
It was ported to the https://github.com/furrtek/portapack-havoc project for the HackRF. Check it out

**Comment by notpike** [comment]
^^^ What this man just said. :D
You'll need the PortaPack but if you look into ASK OOK with GNU Radio you could hack something together. https://zeta-two.com/radio/2015/06/23/ook-ask-sdr.html 

ATM I'm focusing my efforts getting this to work with an Arduino! Figure this project would be more fun if it could be done with $10 instead of $120 for the YSO, or $500 with the HackRF + PortaPack.

**Comment by iflippedmyself** [comment]
i have rewritten your code to work with the very inexpensive transceivers from amazon. i am still in the testing process and my only issue at the moment is the total time it takes to send a transmission signal if you could tell me the time frame i can send you my updated code.


UCEC XY-MK-5V / XY-FST 433Mhz Rf Transmitter and Receiver Module Link Kit for Arduino/Arm/McU/Raspberry pi/Wireless DIY(6-pack)

**Comment by notpike** [comment]
Cool! 

Time frame? Are you asking for the symble length in time or something else?

I'm figuring out how to dev for arduino right now so if you would upload your work on your forked repo we could test it before pushing it to main. :3

**Comment by iflippedmyself** [comment]
since it is ook protocol i am wondering how long an "ON" (binary 1) is high for on on your spectrum analyzer

i am sending raw binary into a rf transmitter and setting the time between each bit with a sleep command.

**Comment by notpike** [comment]
The symbol rate is 1766 bits per sec so...
1 sec / 1766 bits == so each symbol transmits for 0.0005662514156285391sec or ~566us. 

If you like there's an easier way then calling the sleep function between each transmit, check out https://github.com/sui77/rc-switch. I forked a copy and added NEC encoding which is how this remote transmits. https://github.com/notpike/rc-switch/blob/master/RCSwitch.cpp#L83

Not tested but its a start! :D
